# Generated by Django 5.1.6 on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_emailverificationtoken_user_is_active_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
