# Generated by Django 5.2.16 on 2026-09-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_author',
            field=models.BooleanField(default=False, help_text='May create, edit and publish blog posts in the Studio.'),
        ),
    ]
