# Generated by Django 5.2.16 on 2026-09-24 09:17

import django.db.models.deletion
import homepage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('label', models.CharField(blank=True, help_text="Short tag, e.g. 'First-time buyers'.", max_length=80)),
                ('icon', models.CharField(choices=[('home', 'Home'), ('savings', 'Savings'), ('green', 'Green'), ('construction', 'Construction'), ('equity', 'Equity'), ('retirement', 'Retirement')], default='home', max_length=20)),
                ('amount_text', models.CharField(help_text="Display amount, e.g. 'Up to $40,000'.", max_length=80)),
                ('description', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('reviewed_at', models.DateField(blank=True, help_text='When the amount was last verified.', null=True)),
            ],
            options={
                'verbose_name': 'buyer incentive',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_key', models.CharField(max_length=120, unique=True)),
                ('city_label', models.CharField(max_length=120)),
                ('image_url', models.URLField()),
                ('credit', models.CharField(blank=True, max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['city_label'],
            },
        ),
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(help_text="'gta' or a lower-cased city.", max_length=60, unique=True)),
                ('payload', models.JSONField()),
                ('as_of', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('feed_url', models.URLField(unique=True)),
                ('tag', models.CharField(blank=True, help_text="Default tag, e.g. 'Mortgage Rates'.", max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(help_text="e.g. 'Mortgage', 'Legal', 'Inspection'.", max_length=80)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'partner',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoldBelowPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_key', models.CharField(max_length=64, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('property_sub_type', models.CharField(blank=True, max_length=120)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close_date', models.DateField()),
                ('previous_close_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_close_date', models.DateField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-close_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('consent_at', models.DateTimeField()),
                ('consent_text', models.TextField()),
                ('source', models.CharField(default='homepage', max_length=80)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('token', models.CharField(default=homepage.models._token, editable=False, max_length=64, unique=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('tag', models.CharField(blank=True, max_length=60)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hide an off-topic item without deleting it.')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='homepage.newssource')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NearbyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('label', models.CharField(help_text="What the person typed, e.g. '12 Elm St, Oakville'.", max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_km', models.DecimalField(decimal_places=1, default=1, max_digits=4)),
                ('consent_at', models.DateTimeField()),
                ('consent_text', models.TextField(blank=True)),
                ('token', models.CharField(default=homepage.models._token, editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nearby_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'last_notified_at'], name='homepage_ne_is_acti_525168_idx')],
            },
        ),
    ]
