# Generated by Django 4.2 on 2025-09-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0002_alter_accesstoken_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='access_token',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
