version: '3'

services:
  backend:
    build:
      context: ./backend  # Path to your backend Dockerfile
      dockerfile: Dockerfile.dev  # Use your production Dockerfile
    command: uvicorn backend.asgi:application --host 0.0.0.0 --port 8000 --workers 2  # Command to run the backend
    container_name: django_backend
    # environment:
      # Uncomment and set your environment variables here
      # - MODE=${MODE}
      # - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"  # Expose port 8000 for backend (you won't need to access it directly)
    networks:
      - app_network  # Connect to the same network as the frontend and NGINX

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        MODE: "production"
    command: npm start  # Use npm start for Next.js
    container_name: frontend
    networks:
      - app_network
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    restart: on-failure

  nginx:
    image: nginx:latest  # Official NGINX image
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"  # Expose NGINX on port 80 (default HTTP port)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount a custom NGINX config file
    depends_on:
      - frontend
      - backend
    networks:
      - app_network  # Connect to the same network as frontend and backend

networks:
  app_network:
    driver: bridge  # This ensures the containers can communicate with each other
