services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: uvicorn backend.asgi:application --host 0.0.0.0 --port 8000 --workers 2
    container_name: django_backend
    environment:
      - PYTHONUNBUFFERED=1
      # - DATABASE_URL=${DATABASE_URL}
      # - SECRET_KEY=${SECRET_KEY}
      # - DEBUG=False
    expose:
      - "8000"
    networks:
      - app_network
    restart: on-failure
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000:8000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - app_network
    restart: always

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: celery -A backend worker --loglevel=info
    container_name: celery_worker
    depends_on:
      - redis
      - backend
    networks:
      - app_network
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        MODE: "production"
    container_name: frontend
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    networks:
      - app_network
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000:3000"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  caddy:
    image: caddy:latest
    container_name: caddy_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    networks:
      - app_network
    restart: on-failure
    environment:
      - ACME_AGREE=true

networks:
  app_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: