// configs/brandA.config.ts
export const brandConfig = {
  name: "Brand A",
  logo: "/brands/brandA/logo.svg",
  favicon: "/brands/brandA/favicon.ico",
  primaryColor: "#1D4ED8",
  secondaryColor: "#FBBF24",
  apiBaseUrl: "https://api.brandA.com",
  popularNeighborhoods: [
    { name: 'Downtown Toronto', listings: 342, avgPrice: '$1.2M', image: 'https://images.pexels.com/photos/1519088/pexels-photo-1519088.jpeg?auto=compress&cs=tinysrgb&w=400' },
    { name: 'Yorkville', listings: 89, avgPrice: '$2.1M', image: 'https://images.pexels.com/photos/1370704/pexels-photo-1370704.jpeg?auto=compress&cs=tinysrgb&w=400' },
    { name: 'North York', listings: 256, avgPrice: '$980K', image: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=400' },
    { name: 'Etobicoke', listings: 178, avgPrice: '$850K', image: 'https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg?auto=compress&cs=tinysrgb&w=400' },
  ],
  recentListings:  [
    {
      id: 4,
      title: 'Charming Bungalow in North York',
      price: '$1,150,000',
      address: '234 Sheppard Ave, North York, ON',
      beds: 3,
      baths: 2,
      sqft: '1,800',
      image: 'https://images.pexels.com/photos/1732414/pexels-photo-1732414.jpeg?auto=compress&cs=tinysrgb&w=800',
      daysOnMarket: 5,
    },
    {
      id: 5,
      title: 'Contemporary Townhouse',
      price: '$1,350,000',
      address: '567 Yonge St, Toronto, ON',
      beds: 3,
      baths: 2.5,
      sqft: '2,100',
      image: 'https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg?auto=compress&cs=tinysrgb&w=800',
      daysOnMarket: 2,
    },
    {
      id: 6,
      title: 'Elegant Detached Home',
      price: '$1,890,000',
      address: '890 Bloor St W, Toronto, ON',
      beds: 4,
      baths: 3,
      sqft: '2,900',
      image: 'https://images.pexels.com/photos/1370704/pexels-photo-1370704.jpeg?auto=compress&cs=tinysrgb&w=800',
      daysOnMarket: 7,
    },
    {
      id: 7,
      title: 'Cozy Starter Home',
      price: '$749,000',
      address: '321 Danforth Ave, Toronto, ON',
      beds: 2,
      baths: 1,
      sqft: '1,100',
      image: 'https://images.pexels.com/photos/323705/pexels-photo-323705.jpeg?auto=compress&cs=tinysrgb&w=800',
      daysOnMarket: 3,
    },
  ],
listings: [
    {
      id: 1,
      title: 'Modern Condo in Downtown Toronto',
      price: '$899,000',
      address: '123 King St W, Toronto, ON',
      beds: 2,
      baths: 2,
      sqft: '1,200',
      image: 'https://images.pexels.com/photos/1743231/pexels-photo-1743231.jpeg?auto=compress&cs=tinysrgb&w=800',
      status: 'For Sale',
      type: 'Condo',
      featured: true,
    },
    {
      id: 2,
      title: 'Luxury Family Home in Yorkville',
      price: '$2,450,000',
      address: '456 Avenue Rd, Toronto, ON',
      beds: 4,
      baths: 3,
      sqft: '3,500',
      image: 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800',
      status: 'For Sale',
      type: 'House',
      featured: true,
    },
    {
      id: 3,
      title: 'Waterfront Penthouse',
      price: '$3,200,000',
      address: '789 Queens Quay, Toronto, ON',
      beds: 3,
      baths: 3,
      sqft: '2,800',
      image: 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=800',
      status: 'New',
      type: 'Penthouse',
      featured: true,
    },
  ],

};
