"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
import dj_database_url
from dotenv import load_dotenv
from celery.schedules import crontab


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load env values from local-first files, then .env fallback files.
# Keep override=False so real environment variables retain highest priority.
for _env_path in (
    BASE_DIR / ".env.local",
    BASE_DIR.parent / ".env.local",
    BASE_DIR / ".env",
    BASE_DIR.parent / ".env",
):
    load_dotenv(_env_path, override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-oaaa%9e+w*u8tv-u==dtu9(9rlp_akhahh!+5udiy%m3syaivx')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'
IS_VERCEL = os.environ.get("VERCEL") == "1" or bool(os.environ.get("VERCEL_ENV"))

LOCAL_NETWORK_IP = os.environ.get("LOCAL_NETWORK_IP", "192.168.1.29")

ALLOWED_HOSTS = ['staging.vsell4u.ca', 'localhost', '127.0.0.1', '.vercel.app', LOCAL_NETWORK_IP]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    "ckeditor",
    "ckeditor_uploader",
    "vlog",
    "mls",
    "accounts",
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_spectacular",
    "cloudinary",
    "cloudinary_storage",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

_database_url = os.environ.get('DATABASE_URL', 'postgresql://neondb_owner:npg_9JxAXdt5ZbNn@ep-young-river-adbytfzk-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require')
DATABASES = {
    'default': dj_database_url.config(
        default=_database_url,
        conn_max_age=600,
        ssl_require=_database_url.startswith(("postgres://", "postgresql://")),
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://redis:6379/0")

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = os.environ.get("CELERY_TIMEZONE", "UTC")

# Local dev: run tasks synchronously without a broker (set in .env.local).
CELERY_TASK_ALWAYS_EAGER = os.environ.get("CELERY_TASK_ALWAYS_EAGER", "False") == "True"
CELERY_TASK_EAGER_PROPAGATES = os.environ.get("CELERY_TASK_EAGER_PROPAGATES", "False") == "True"

if os.environ.get("DAILY_NEWSLETTER_BEAT_ENABLED", "0") == "1":
    CELERY_BEAT_SCHEDULE = {
        "send-daily-listing-newsletters": {
            "task": "mls.tasks.run_daily_listing_newsletters",
            "schedule": crontab(
                hour=int(os.environ.get("DAILY_NEWSLETTER_HOUR_UTC", "11")),
                minute=int(os.environ.get("DAILY_NEWSLETTER_MINUTE_UTC", "0")),
            ),
        },
    }


CACHE_URL = os.environ.get("CACHE_URL", os.environ.get("REDIS_URL", "")).strip()
if CACHE_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": CACHE_URL,
            "TIMEOUT": int(os.environ.get("DJANGO_CACHE_TIMEOUT", "300")),
            "KEY_PREFIX": os.environ.get("DJANGO_CACHE_KEY_PREFIX", "mls-v2"),
        }
    }
else:
    # Safe local fallback when Redis is not configured.
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "mls-v2-local-cache",
            "TIMEOUT": int(os.environ.get("DJANGO_CACHE_TIMEOUT", "300")),
            "KEY_PREFIX": os.environ.get("DJANGO_CACHE_KEY_PREFIX", "mls-v2"),
        }
    }


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Cloudinary Storage
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}

# Estate image uploads are intentionally Cloudinary-only.  Keeping this
# separate from the default storage setting prevents an admin upload from
# quietly landing on a transient application filesystem.
ESTATE_IMAGE_MAX_UPLOAD_MB = int(os.environ.get("ESTATE_IMAGE_MAX_UPLOAD_MB", "10"))

# Enable Cloudinary storage only when configuration is complete.
# This avoids runtime failures when only partial credentials are present.
_cloudinary_url = (os.environ.get("CLOUDINARY_URL") or "").strip()
_cloudinary_complete = all(
    [
        (os.environ.get("CLOUDINARY_CLOUD_NAME") or "").strip(),
        (os.environ.get("CLOUDINARY_API_KEY") or "").strip(),
        (os.environ.get("CLOUDINARY_API_SECRET") or "").strip(),
    ]
)
if IS_VERCEL:
    _staticfiles_backend = "whitenoise.storage.CompressedStaticFilesStorage"
    WHITENOISE_USE_FINDERS = True
else:
    _staticfiles_backend = "whitenoise.storage.CompressedManifestStaticFilesStorage"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": _staticfiles_backend,
    },
}

if _cloudinary_url or _cloudinary_complete:
    STORAGES["default"]["BACKEND"] = "cloudinary_storage.storage.MediaCloudinaryStorage"
    # Keep compatibility with codepaths still checking this setting.
    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

ESTATE_IMAGE_STORAGE_CONFIGURED = bool(_cloudinary_url or _cloudinary_complete)

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")] 

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# path inside MEDIA_ROOT where ckeditor uploads go
CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Full',
        'height': 300,
        'width': '100%',
        'extraPlugins': ','.join([
            # add plugins if needed, e.g. 'youtube' (ensure plugin available)
        ]),
    },
}
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    f"http://{LOCAL_NETWORK_IP}:3000",
    "https://staging.vsell4u.ca",
    "http://staging.vsell4u.ca",
    "https://mls-frontend-v2.vercel.app",
]
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://(.+\.)?vercel\.app$",
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    f"http://{LOCAL_NETWORK_IP}:3000",
    "https://staging.vsell4u.ca",
    "http://staging.vsell4u.ca",
    "https://mls-frontend-v2.vercel.app",
]

CORS_ALLOW_CREDENTIALS = True

CLIENT_ID = 'uCyucNP7QrV4fLA8YtWngTUg'
CLIENT_SECRET = 'OFocUcAnQShbZRPUKdaafgEi'

AUTH_USER_MODEL = 'accounts.User'

# Google OAuth
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '909407398208-ftdd1k2p9lr6rk2t7ivop3bbfp8q6b7o.apps.googleusercontent.com')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')

# Facebook OAuth (Login with Facebook — authorization code flow)
FACEBOOK_APP_ID = os.environ.get('FACEBOOK_APP_ID', '').strip()
FACEBOOK_APP_SECRET = os.environ.get('FACEBOOK_APP_SECRET', '').strip()
FACEBOOK_REDIRECT_URI = os.environ.get(
    'FACEBOOK_REDIRECT_URI',
    'http://localhost:3000/auth/facebook/callback',
).strip()
FACEBOOK_GRAPH_VERSION = os.environ.get('FACEBOOK_GRAPH_VERSION', 'v19.0').strip().lstrip('/')
# Comma-separated list of extra redirect URIs allowed when client sends redirect_uri (e.g. staging + prod)
FACEBOOK_ALLOWED_REDIRECT_URIS = os.environ.get('FACEBOOK_ALLOWED_REDIRECT_URIS', '').strip()

# GoHighLevel
GHL_API_KEY = os.environ.get('GHL_API_KEY', '')
GHL_LOCATION_ID = os.environ.get('GHL_LOCATION_ID', '')
GHL_USER_ID = os.environ.get('GHL_USER_ID', '')

# Twilio Verify (phone OTP)
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_VERIFY_SERVICE_SID = os.environ.get('TWILIO_VERIFY_SERVICE_SID', '')

# Email (realtor notifications, etc.)
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@vsell4u.ca')
SENDGRID_API_KEY = os.environ.get('SENDGRID_API_KEY', '')
SENDGRID_BASE_URL = os.environ.get('SENDGRID_BASE_URL', 'https://api.sendgrid.com/v3')
SENDGRID_TIMEOUT_SECONDS = int(os.environ.get('SENDGRID_TIMEOUT_SECONDS', '15'))
REALTOR_INBOX_EMAIL = os.environ.get('REALTOR_INBOX_EMAIL', '')
# Base URL for links in outbound emails (e.g. Django admin change URL)
PUBLIC_BACKEND_URL = os.environ.get('PUBLIC_BACKEND_URL', 'http://127.0.0.1:8000')

# Frontend base URL — used when building email links (e.g. verification links).
# Example: https://app.ravan.ai   or   https://staging.vsell4u.ca
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'https://app.ravan.ai')

# How long (in hours) a verification token stays valid. Default: 24 h.
EMAIL_VERIFICATION_EXPIRY_HOURS = int(os.environ.get('EMAIL_VERIFICATION_EXPIRY_HOURS', '24'))

# DRF
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'VSell4U MLS API',
    'DESCRIPTION': (
        'API documentation for listings, property search, inquiries, user accounts, '
        'watched properties, and related MLS services.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SERVE_AUTHENTICATION': ['rest_framework_simplejwt.authentication.JWTAuthentication'],
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'Health', 'description': 'Application liveness and database readiness checks.'},
        {'name': 'Authentication', 'description': 'Account registration, authentication, verification, and profile operations.'},
        {'name': 'Estate Projects', 'description': 'Published canonical estate project data.'},
        {'name': 'Estate Documents', 'description': 'Phone-aware access to canonical estate project documents.'},
        {'name': 'Estate Properties (Legacy)', 'description': 'Legacy estate-property administration and compatibility endpoints.'},
        {'name': 'MLS Properties', 'description': 'MLS listing retrieval and related property data.'},
        {'name': 'Property Search', 'description': 'Structured property search and filtering.'},
        {'name': 'Maps', 'description': 'Location, school, amenity, and census data.'},
        {'name': 'Valuation', 'description': 'Property valuation lookup and estimates.'},
        {'name': 'Inquiries', 'description': 'Property inquiries and visitor feedback.'},
        {'name': 'User Activity', 'description': 'Listing engagement, views, and property notes.'},
        {'name': 'Watched Properties', 'description': 'Favorites, history, tours, and followed areas.'},
        {'name': 'Alerts', 'description': 'Watched-property alert preferences and previews.'},
        {'name': 'Vlogs', 'description': 'Published vlog content.'},
    ],
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'docExpansion': 'none',
        'filter': True,
        'defaultModelsExpandDepth': -1,
    },
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.hooks.postprocess_schema_enums',
        'backend.schema.assign_api_tags',
    ],
}

ESTATE_DOCUMENT_ALLOWED_HOSTS = [
    host.strip().lower()
    for host in os.environ.get(
        "ESTATE_DOCUMENT_ALLOWED_HOSTS",
        "estate-4u.com,res.cloudinary.com",
    ).split(",")
    if host.strip()
]
ESTATE_DOCUMENT_ACCESS_MAX_AGE = int(os.environ.get("ESTATE_DOCUMENT_ACCESS_MAX_AGE", "300"))
ESTATE_DOCUMENT_MAX_BYTES = int(os.environ.get("ESTATE_DOCUMENT_MAX_BYTES", str(25 * 1024 * 1024)))

# JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
}
if os.environ.get("DJANGO_TEST_WITHOUT_MIGRATIONS") == "1":
    MIGRATION_MODULES = {"mls": None}
