# Generated by Django 4.2 on 2026-04-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlogpost',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='If true, automated sync will not overwrite this post'),
        ),
    ]
