# Generated by Django 4.2 on 2026-04-28 09:29

from django.db import migrations, models
import vlog.models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0002_vlogpost_is_manual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vlogcategory',
            options={'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AlterModelOptions(
            name='vlogpost',
            options={'ordering': ['-publish_date', '-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AddField(
            model_name='vlogpost',
            name='og_description',
            field=models.TextField(blank=True, help_text='Optional Open Graph description override'),
        ),
        migrations.AddField(
            model_name='vlogpost',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Optional Open Graph image override', null=True, upload_to=vlog.models.thumbnail_upload_path),
        ),
        migrations.AddField(
            model_name='vlogpost',
            name='og_title',
            field=models.CharField(blank=True, help_text='Optional Open Graph title override', max_length=255),
        ),
        migrations.AddField(
            model_name='vlogpost',
            name='seo_canonical_url',
            field=models.URLField(blank=True, help_text='Optional canonical URL override'),
        ),
        migrations.AddField(
            model_name='vlogpost',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Optional meta description override'),
        ),
        migrations.AddField(
            model_name='vlogpost',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=500),
        ),
        migrations.AddField(
            model_name='vlogpost',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='When enabled, search engines are asked not to index this post'),
        ),
        migrations.AddField(
            model_name='vlogpost',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Optional SEO title override', max_length=255),
        ),
    ]
