# Generated by Django 4.2 on 2026-04-28 09:41

from django.db import migrations, models
import vlog.models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0003_alter_vlogcategory_options_alter_vlogpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlogpost',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary target keyword for this post', max_length=255),
        ),
        migrations.AddField(
            model_name='vlogpost',
            name='twitter_description',
            field=models.TextField(blank=True, help_text='Optional Twitter description override'),
        ),
        migrations.AddField(
            model_name='vlogpost',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Optional Twitter image override', null=True, upload_to=vlog.models.thumbnail_upload_path),
        ),
        migrations.AddField(
            model_name='vlogpost',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Optional Twitter title override', max_length=255),
        ),
    ]
