# Generated by Django 4.2 on 2026-04-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0004_vlogpost_focus_keyword_vlogpost_twitter_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlogpost',
            name='faq_items',
            field=models.JSONField(blank=True, default=list, help_text="Optional FAQ entries as [{'question': '...', 'answer': '...'}]"),
        ),
    ]
