# Generated by Django 4.2 on 2025-12-04 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0003_alter_accesstoken_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_key', models.CharField(max_length=255, unique=True)),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('property_type', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state_or_province', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('lot_size', models.CharField(blank=True, max_length=255, null=True)),
                ('pool_features', models.TextField(blank=True, null=True)),
                ('waterfront_features', models.TextField(blank=True, null=True)),
                ('appliances', models.TextField(blank=True, null=True)),
                ('security_features', models.TextField(blank=True, null=True)),
                ('listing_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photos_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('parking_total', models.IntegerField(blank=True, null=True)),
                ('heating', models.TextField(blank=True, null=True)),
                ('cooling', models.TextField(blank=True, null=True)),
                ('tax_annual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=255)),
                ('room_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_level', models.CharField(blank=True, max_length=255, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='mls.property')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.URLField()),
                ('media_category', models.CharField(max_length=255)),
                ('is_preferred', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='mls.property')),
            ],
        ),
    ]
