# Generated by Django 4.2 on 2025-12-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0005_rename_address_property_above_grade_finished_area_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_attached_yn',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
