# Generated by Django 4.2 on 2025-12-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0007_alter_property_fireplace_yn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category_type',
            field=models.CharField(choices=[('exclusive', 'Exclusive'), ('pre_conn', 'Pre-Connected')], default='exclusive', max_length=20),
        ),
    ]
