# Generated by Django 4.2 on 2025-12-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0008_property_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category_type',
            field=models.CharField(blank=True, choices=[('exclusive', 'Exclusive'), ('pre_conn', 'Pre-Connected')], default='exclusive', max_length=20, null=True),
        ),
    ]
