# Generated by Django 4.2 on 2025-12-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0010_alter_media_media_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_category',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_url',
            field=models.URLField(max_length=2000),
        ),
    ]
