# Generated by Django 4.2 on 2026-04-25 11:41

from django.db import migrations, models
import mls.models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0011_alter_media_media_category_alter_media_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_file',
            field=models.ImageField(blank=True, null=True, upload_to=mls.models.property_media_path),
        ),
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='If true, automated sync will not overwrite this listing'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category_type',
            field=models.CharField(blank=True, choices=[('exclusive', 'Exclusive'), ('pre_conn', 'Pre-Connected'), ('ddf', 'MLS Sync')], default=None, max_length=20, null=True),
        ),
    ]
