# Generated by Django 4.2 on 2026-04-26 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0014_property_ai_summary_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mapaggregatecell',
            new_name='mls_mapaggr_resolut_46a66b_idx',
            old_name='mls_mapaggr_resolut_52c0de_idx',
        ),
        migrations.RenameIndex(
            model_name='mapaggregatecell',
            new_name='mls_mapaggr_resolut_b0bbd3_idx',
            old_name='mls_mapaggr_resolut_af2b7b_idx',
        ),
        migrations.RenameIndex(
            model_name='mapaggregatecell',
            new_name='mls_mapaggr_resolut_427157_idx',
            old_name='mls_mapaggr_resolut_0df091_idx',
        ),
    ]
