# Generated by Django 4.2 on 2026-04-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mls", "0015_rename_mls_mapaggr_resolut_52c0de_idx_mls_mapaggr_resolut_46a66b_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_url", models.URLField(blank=True, max_length=2000, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("bug", "Bug Report"),
                            ("feature", "Feature Request"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("status", models.CharField(default="new", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
