# Generated by Django 4.2 on 2026-04-26 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mls', '0016_userfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_key', models.CharField(max_length=255)),
                ('property_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_key', models.CharField(max_length=255)),
                ('property_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['user', '-viewed_at'], name='mls_userhis_user_id_0b7728_idx'),
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['property_key'], name='mls_userhis_propert_e0fa5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='userhistory',
            constraint=models.UniqueConstraint(fields=('user', 'property_key'), name='unique_user_history_property_key'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['user', '-created_at'], name='mls_userfav_user_id_2d0e10_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['property_key'], name='mls_userfav_propert_772679_idx'),
        ),
        migrations.AddConstraint(
            model_name='userfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'property_key'), name='unique_user_favorite_property_key'),
        ),
    ]
