# Generated by Django 4.2 on 2026-04-26 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mls', '0017_userhistory_userfavorite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('intent', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('rent', 'Rent'), ('explore', 'Just Exploring')], default='buy', max_length=20)),
                ('message', models.TextField(help_text='Free-form description from the user')),
                ('preferred_locations', models.CharField(blank=True, max_length=500)),
                ('property_types', models.CharField(blank=True, max_length=255)),
                ('budget_min', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_max', models.PositiveIntegerField(blank=True, null=True)),
                ('bedrooms_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('timeline', models.CharField(blank=True, max_length=80)),
                ('page_url', models.URLField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('ghl_contact_id', models.CharField(blank=True, max_length=255)),
                ('ghl_synced_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='propertyinquiry',
            index=models.Index(fields=['status', 'created_at'], name='mls_propert_status_8b5be8_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinquiry',
            index=models.Index(fields=['email'], name='mls_propert_email_68e812_idx'),
        ),
    ]
