# Generated by Django 5.2.13 on 2026-05-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0018_propertyinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='internet_address_display_yn',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
