# Generated by Django 5.2.13 on 2026-05-04 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0019_property_internet_address_display_yn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusFSA',
            fields=[
                ('fsa', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_key', models.CharField(db_index=True, max_length=2000)),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('standard_status', models.CharField(blank=True, max_length=80)),
                ('source_modification_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing_key', '-created_at'], name='mls_propert_listing_98c527_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListingViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_key', models.CharField(db_index=True, max_length=2000)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_view_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing_key', 'created_at'], name='mls_listing_listing_a54cad_idx'), models.Index(fields=['session_key', 'listing_key'], name='mls_listing_session_c33252_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_key', models.CharField(db_index=True, max_length=2000)),
                ('body', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'listing_key'), name='uniq_propertynote_user_listing_key')],
            },
        ),
    ]
