# Generated by Django 5.2.13 on 2026-05-05 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0021_communitylisting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_changes', models.BooleanField(default=True)),
                ('new_listings', models.BooleanField(default=True)),
                ('status_updates', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_key', models.CharField(max_length=255)),
                ('area_label', models.CharField(max_length=255)),
                ('area_kind', models.CharField(choices=[('community', 'Community'), ('neighborhood', 'Neighborhood'), ('region', 'Region'), ('city', 'City')], default='community', max_length=40)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserToured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_key', models.CharField(max_length=255)),
                ('property_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('toured_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-toured_at'],
            },
        ),
        migrations.AddField(
            model_name='useralertpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfollowedarea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_areas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertoured',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_toured', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userfollowedarea',
            index=models.Index(fields=['user', '-created_at'], name='mls_userfol_user_id_fc6c80_idx'),
        ),
        migrations.AddIndex(
            model_name='userfollowedarea',
            index=models.Index(fields=['area_key'], name='mls_userfol_area_ke_458326_idx'),
        ),
        migrations.AddConstraint(
            model_name='userfollowedarea',
            constraint=models.UniqueConstraint(fields=('user', 'area_key'), name='unique_user_followed_area_key'),
        ),
        migrations.AddIndex(
            model_name='usertoured',
            index=models.Index(fields=['user', '-toured_at'], name='mls_usertou_user_id_9ceca5_idx'),
        ),
        migrations.AddIndex(
            model_name='usertoured',
            index=models.Index(fields=['property_key'], name='mls_usertou_propert_ae817a_idx'),
        ),
        migrations.AddConstraint(
            model_name='usertoured',
            constraint=models.UniqueConstraint(fields=('user', 'property_key'), name='unique_user_toured_property_key'),
        ),
    ]
