# Generated by Django 5.2.13 on 2026-05-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0022_useralertpreference_userfollowedarea_usertoured_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communitylisting',
            new_name='mls_communi_communi_1989bb_idx',
            old_name='mls_communi_communi_090667_idx',
        ),
    ]
