# Generated by Django 5.2.13 on 2026-05-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0025_userpropertyinteraction_searchevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentservicearea',
            new_name='mls_agentse_kind_a14dba_idx',
            old_name='mls_agentser_kind_3e4f5a_idx',
        ),
        migrations.RenameIndex(
            model_name='propertysoldproxy',
            new_name='mls_propert_fsa_2c22b5_idx',
            old_name='mls_propert_fsa_0a8b8d_idx',
        ),
        migrations.RenameIndex(
            model_name='propertysoldproxy',
            new_name='mls_propert_latitud_ce8c09_idx',
            old_name='mls_propert_latitud_8f1c2e_idx',
        ),
        migrations.RenameIndex(
            model_name='searchevent',
            new_name='mls_searche_user_id_97bc0d_idx',
            old_name='mls_searchev_user_id_24edce_idx',
        ),
        migrations.RenameIndex(
            model_name='searchevent',
            new_name='mls_searche_session_bfb134_idx',
            old_name='mls_searchev_session_46f2fe_idx',
        ),
        migrations.RenameIndex(
            model_name='searchevent',
            new_name='mls_searche_city_3291b1_idx',
            old_name='mls_searchev_city_3f479c_idx',
        ),
        migrations.RenameIndex(
            model_name='userpropertyinteraction',
            new_name='mls_userpro_event_t_4ee7e5_idx',
            old_name='mls_userprop_event_t_9071e9_idx',
        ),
        migrations.RenameIndex(
            model_name='userpropertyinteraction',
            new_name='mls_userpro_user_id_2d7565_idx',
            old_name='mls_userprop_user_id_cf2a28_idx',
        ),
        migrations.RenameIndex(
            model_name='userpropertyinteraction',
            new_name='mls_userpro_session_3c7016_idx',
            old_name='mls_userprop_session_ab4e6d_idx',
        ),
        migrations.RenameIndex(
            model_name='userpropertyinteraction',
            new_name='mls_userpro_listing_0822f6_idx',
            old_name='mls_userprop_listing_e4ef5c_idx',
        ),
    ]
