# Generated by Codex on 2026-05-18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mls", "0036_estateproperty_listing_buttons"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="useralertpreference",
            name="email_recommend",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="useralertpreference",
            name="email_watched_area",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="useralertpreference",
            name="email_watched_community",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="useralertpreference",
            name="email_watched_property",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="useralertpreference",
            name="push_watched_property",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ListingFirstSeen",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("listing_key", models.CharField(db_index=True, max_length=2000, unique=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("first_source_modification_timestamp", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-first_seen_at"],
                "indexes": [models.Index(fields=["-first_seen_at"], name="mls_listing_first_s_078039_idx")],
            },
        ),
        migrations.CreateModel(
            name="NewsletterDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("digest_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("skipped", "Skipped"), ("failed", "Failed")],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("listing_count", models.PositiveIntegerField(default=0)),
                ("section_counts", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletter_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["digest_date", "status"], name="mls_newslet_digest__121f03_idx"),
                    models.Index(fields=["user", "-created_at"], name="mls_newslet_user_id_c77531_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "digest_date"),
                        name="uniq_newsletterdelivery_user_digest_date",
                    )
                ],
            },
        ),
    ]
