# Generated by Django 5.2.14 on 2026-07-15 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0037_newsletter_preferences_and_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='wordpress', max_length=40)),
                ('source_id', models.CharField(max_length=200)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('publication_status', models.CharField(db_index=True, default='draft', max_length=40)),
                ('developer', models.CharField(blank=True, max_length=500)),
                ('occupancy_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=1000)),
                ('city', models.CharField(blank=True, db_index=True, max_length=255)),
                ('province', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('featured_image_url', models.URLField(blank=True, max_length=2000)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'title'],
                'indexes': [models.Index(fields=['publication_status', 'city'], name='mls_estatep_publica_4b4369_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_id'), name='uniq_estate_source_id')],
            },
        ),
        migrations.CreateModel(
            name='EstateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('source_key', models.CharField(blank=True, default='', max_length=255)),
                ('parser_owned', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=500)),
                ('document_type', models.CharField(choices=[('floor_plan', 'Floor plan'), ('brochure', 'Brochure'), ('price_list', 'Price list'), ('other', 'Other')], default='other', max_length=30)),
                ('source_url', models.URLField(max_length=3000)),
                ('requires_phone_verification', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mls.estateproject')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstateContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('source_key', models.CharField(blank=True, default='', max_length=255)),
                ('parser_owned', models.BooleanField(default=False)),
                ('heading', models.CharField(blank=True, max_length=500)),
                ('html', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='mls.estateproject')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstateAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('source_key', models.CharField(blank=True, default='', max_length=255)),
                ('parser_owned', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('travel_time_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='mls.estateproject')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstateSourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_html', models.TextField(blank=True)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('raw_terms', models.JSONField(blank=True, default=dict)),
                ('raw_post', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('imported_project_values', models.JSONField(blank=True, default=dict)),
                ('parser_version', models.PositiveSmallIntegerField(default=0)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_snapshot', to='mls.estateproject')),
            ],
        ),
        migrations.CreateModel(
            name='EstateUnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('source_key', models.CharField(blank=True, default='', max_length=255)),
                ('parser_owned', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_types', to='mls.estateproject')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstatePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('source_key', models.CharField(blank=True, default='', max_length=255)),
                ('parser_owned', models.BooleanField(default=False)),
                ('display_text', models.CharField(max_length=1000)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='mls.estateproject')),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='mls.estateunittype')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstateDepositPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('source_key', models.CharField(blank=True, default='', max_length=255)),
                ('parser_owned', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_plans', to='mls.estateproject')),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_plans', to='mls.estateunittype')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstateDepositInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('source_key', models.CharField(blank=True, default='', max_length=255)),
                ('parser_owned', models.BooleanField(default=False)),
                ('milestone', models.CharField(max_length=500)),
                ('amount_text', models.CharField(max_length=1000)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='mls.estatedepositplan')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('plan', 'source_key'), name='uniq_estate_installment_source')],
            },
        ),
        migrations.CreateModel(
            name='EstateDocumentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='mls.estatedocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_document_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'document', '-created_at'], name='mls_estated_user_id_a83475_idx')],
            },
        ),
        migrations.CreateModel(
            name='EstateIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('source_key', models.CharField(blank=True, default='', max_length=255)),
                ('parser_owned', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='mls.estateproject')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('project', 'source_key'), name='uniq_estate_incentive_source')],
            },
        ),
        migrations.AddConstraint(
            model_name='estatedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('project', 'source_key'), name='uniq_estate_document_source'),
        ),
        migrations.AddConstraint(
            model_name='estatecontentsection',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('project', 'source_key'), name='uniq_estate_section_source'),
        ),
        migrations.AddConstraint(
            model_name='estateamenity',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('project', 'source_key'), name='uniq_estate_amenity_source'),
        ),
        migrations.AddConstraint(
            model_name='estateunittype',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('project', 'source_key'), name='uniq_estate_unit_source'),
        ),
        migrations.AddConstraint(
            model_name='estateprice',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('project', 'source_key'), name='uniq_estate_price_source'),
        ),
        migrations.AddConstraint(
            model_name='estatedepositplan',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('project', 'source_key'), name='uniq_estate_deposit_source'),
        ),
    ]
