# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mls", "0037_newsletter_preferences_and_delivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmplifySoldProperty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("listing_key", models.CharField(db_index=True, max_length=2000, unique=True)),
                ("standard_status", models.CharField(blank=True, max_length=64, null=True)),
                ("list_price", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("close_price", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("sold_price", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("close_date", models.DateField(blank=True, db_index=True, null=True)),
                ("modification_timestamp", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("city", models.CharField(blank=True, max_length=2000, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("fsa", models.CharField(blank=True, db_index=True, max_length=3)),
                ("property_sub_type", models.CharField(blank=True, max_length=2000, null=True)),
                ("bedrooms_total", models.IntegerField(blank=True, null=True)),
                ("bathrooms_total_integer", models.IntegerField(blank=True, null=True)),
                ("living_area", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("days_on_market", models.IntegerField(blank=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["city", "close_date"], name="mls_amplifys_city_7b176c_idx"),
                    models.Index(fields=["fsa", "close_date"], name="mls_amplifys_fsa_3400bd_idx"),
                    models.Index(fields=["modification_timestamp"], name="mls_amplifys_modific_c10671_idx"),
                    models.Index(fields=["-close_date"], name="mls_amplifys_close_d_ef5e17_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AmplifySoldSyncState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(default="default", max_length=32, unique=True)),
                ("last_successful_modification_timestamp", models.DateTimeField(blank=True, null=True)),
                ("last_successful_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempted_sync_at", models.DateTimeField(blank=True, null=True)),
                ("total_rows_synced", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Amplify sold sync state",
                "verbose_name_plural": "Amplify sold sync state",
            },
        ),
    ]
