# Generated by Django 5.2.16 on 2026-07-20 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0042_estate_property_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_id', models.IntegerField(unique=True)),
                ('login', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('display_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_id', models.BigIntegerField(unique=True)),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('page', 'Page'), ('property', 'Property')], max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('content', models.TextField(blank=True)),
                ('excerpt', models.TextField(blank=True)),
                ('status', models.CharField(max_length=30)),
                ('published_at', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mls.author')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('mime_type', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mls.content')),
            ],
        ),
        migrations.CreateModel(
            name='PreComProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('garages', models.PositiveIntegerField(blank=True, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('address', models.TextField(blank=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='mls.content')),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_id', models.IntegerField(unique=True)),
                ('taxonomy', models.CharField(choices=[('category', 'Category'), ('tag', 'Tag'), ('property_city', 'Property City'), ('property_type', 'Property Type'), ('property_status', 'Property Status'), ('property_label', 'Property Label'), ('property_feature', 'Property Feature')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mls.taxonomy')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='taxonomies',
            field=models.ManyToManyField(blank=True, to='mls.taxonomy'),
        ),
        migrations.CreateModel(
            name='ContentMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='mls.content')),
            ],
            options={
                'unique_together': {('content', 'key')},
            },
        ),
    ]
