# Generated by Django 5.2.16 on 2026-07-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0043_author_content_attachment_precomproperty_taxonomy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estateproperty',
            options={'managed': False, 'verbose_name': 'Estate property', 'verbose_name_plural': 'Estate properties'},
        ),
    ]
