# Generated by Django 5.1.4 on 2026-07-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mls", "0045_repair_estateproject_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PreComFloorPlanIntent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_url", models.URLField(max_length=3000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("property", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="floor_plan_intents", to="mls.precomproperty")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="precon_floor_plan_intents", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="precomfloorplanintent",
            index=models.Index(fields=["property", "-created_at"], name="mls_precomf_propert_67e3f8_idx"),
        ),
        migrations.AddIndex(
            model_name="precomfloorplanintent",
            index=models.Index(fields=["user", "-created_at"], name="mls_precomf_user_id_e70f5e_idx"),
        ),
    ]
