# Generated by Django 5.2.16 on 2026-07-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mls", "0046_precomfloorplanintent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mls.author",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("publish", "Published"),
                    ("pending", "Pending review"),
                    ("private", "Private"),
                    ("archived", "Archived"),
                    ("active", "Active (legacy)"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
