# Generated by Django 5.2.16 on 2026-07-23

from django.db import migrations


def create_missing_precom_properties(apps, schema_editor):
    Content = apps.get_model("mls", "Content")
    PreComProperty = apps.get_model("mls", "PreComProperty")

    missing_content_ids = Content.objects.filter(
        content_type="property", property__isnull=True
    ).values_list("id", flat=True)
    PreComProperty.objects.bulk_create(
        [PreComProperty(content_id=content_id) for content_id in missing_content_ids]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("mls", "0047_content_status_choices_and_optional_editor_fields"),
    ]

    operations = [
        migrations.RunPython(
            create_missing_precom_properties,
            migrations.RunPython.noop,
        ),
    ]
