# Generated by Django 5.2.16 on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mls", "0048_create_precom_properties_for_property_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingSyncStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("last_successful_at", models.DateTimeField()),
                ("listing_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "listing sync statuses",
            },
        ),
    ]
