# Generated by Django 5.2.16 on 2026-07-23

import mls.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mls", "0049_listingsyncstatus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("submitter_type", models.CharField(choices=[("owner", "Owner"), ("agent", "Agent"), ("builder", "Builder")], max_length=16)),
                ("purpose", models.CharField(choices=[("sale", "For sale"), ("rent", "For rent")], max_length=8)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("submitted", "Submitted"), ("under_review", "Under review"), ("needs_changes", "Needs changes"), ("approved", "Approved"), ("rejected", "Rejected"), ("withdrawn", "Withdrawn")], default="draft", max_length=20)),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=120)),
                ("province", models.CharField(default="ON", max_length=80)),
                ("postal_code", models.CharField(blank=True, max_length=16)),
                ("country", models.CharField(default="Canada", max_length=80)),
                ("property_type", models.CharField(max_length=100)),
                ("bedrooms", models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ("bathrooms", models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ("interior_area_sqft", models.PositiveIntegerField(blank=True, null=True)),
                ("asking_price", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("available_from", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("contact_name", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=30)),
                ("ownership_confirmed", models.BooleanField(default=False)),
                ("publication_consent", models.BooleanField(default=False)),
                ("review_note", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_listing_submissions", to=settings.AUTH_USER_MODEL)),
                ("submitted_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="listing_submissions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="ListingSubmissionMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("media_type", models.CharField(choices=[("photo", "Photo"), ("floor_plan", "Floor plan"), ("supporting_document", "Supporting document")], default="photo", max_length=24)),
                ("file", models.FileField(upload_to=mls.models.listing_submission_media_upload_path)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("submission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="media", to="mls.listingsubmission")),
            ],
            options={"ordering": ["display_order", "id"]},
        ),
        migrations.AddIndex(model_name="listingsubmission", index=models.Index(fields=["submitted_by", "status"], name="mls_listing_submitt_b2cbf4_idx")),
        migrations.AddIndex(model_name="listingsubmission", index=models.Index(fields=["status", "-submitted_at"], name="mls_listing_status_2994da_idx")),
        migrations.AddIndex(model_name="listingsubmission", index=models.Index(fields=["city", "postal_code"], name="mls_listing_city_0a2cc6_idx")),
    ]
