# Generated by Django 5.2.16 on 2026-07-24 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0050_listingsubmission_listingsubmissionmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_house_key', models.CharField(max_length=255, unique=True)),
                ('listing_id', models.CharField(blank=True, max_length=2000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('open_house_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('livestream_url', models.URLField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_houses', to='mls.property')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date', 'status'], name='mls_openhou_date_d250dd_idx'), models.Index(fields=['property', 'date'], name='mls_openhou_propert_b76935_idx')],
            },
        ),
    ]
