# Generated by Django 5.2.16 on 2026-09-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0052_api_gaps_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinquiry',
            name='intent',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('rent', 'Rent'), ('explore', 'Just Exploring'), ('showing', 'Request a Showing')], default='buy', max_length=20),
        ),
    ]
