# Generated by Django 5.2.16 on 2026-09-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0053_alter_propertyinquiry_intent'),
        ('mls', '0053_gap_backend_api_final'),
    ]

    operations = [
    ]
