# Generated by Django 5.2.16 on 2026-09-23 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0054_merge_20260923_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingsubmission',
            name='assignment_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='listingsubmission',
            name='builder_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='listingsubmission',
            name='deposit_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='listingsubmission',
            name='occupancy_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingsubmission',
            name='original_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='listingsubmission',
            name='precon_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_submissions', to='mls.precomproperty'),
        ),
        migrations.AddField(
            model_name='listingsubmission',
            name='project_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='listingsubmission',
            name='purpose',
            field=models.CharField(choices=[('sale', 'For sale'), ('rent', 'For rent'), ('assignment', 'Assignment')], max_length=12),
        ),
    ]
