"use client";

import { AlertTriangle } from "lucide-react";
import { colors } from "@/config/design-system";

export function BetaBanner() {
  return (
    <div
      className="flex gap-3 rounded-2xl p-4 mb-8 border"
      style={{
        backgroundColor: `${colors.primary}08`,
        borderColor: colors.cardsBoarder,
      }}
    >
      <AlertTriangle
        className="w-6 h-6 flex-shrink-0 mt-0.5"
        style={{ color: colors.icon }}
      />
      <div>
        <p className="font-bold text-sm" style={{ color: colors.heading }}>
          Sigma Estimate (beta)
        </p>
        <p className="text-sm mt-1 leading-relaxed" style={{ color: colors.body }}>
          This estimate is generated by our internal model and is meant as a{" "}
          <strong>starting point only</strong>. It is not a professional appraisal
          or substitute for an on-site evaluation.
        </p>
      </div>
    </div>
  );
}
