from decimal import Decimal

from django.core.management.base import BaseCommand
from django.db import transaction

from mls.models import (
    EstateAmenity,
    EstateContentSection,
    EstateDepositInstallment,
    EstateDepositPlan,
    EstateIncentive,
    EstatePrice,
    EstateProject,
    EstateUnitType,
)


DEMO_PREFIX = "demo-auto:"


def deterministic_base_price(project: EstateProject) -> Decimal:
    """
    Produces a stable demo price between $549,000 and $999,000.
    The same project always gets the same value.
    """
    increments = [
        549000,
        599000,
        649000,
        699000,
        749000,
        799000,
        849000,
        899000,
        949000,
        999000,
    ]
    return Decimal(increments[project.id % len(increments)])


def project_location(project: EstateProject) -> str:
    parts = [
        project.city.strip(),
        project.province.strip(),
    ]
    return ", ".join(part for part in parts if part) or "Ontario"


class Command(BaseCommand):
    help = (
        "Fill missing EstateProject structured content with deterministic "
        "synthetic demo data. Existing real/manual rows are preserved."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--project-id",
            type=int,
            help="Seed one EstateProject only.",
        )
        parser.add_argument(
            "--limit",
            type=int,
            help="Maximum number of projects to process.",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Show what would change without committing.",
        )
        parser.add_argument(
            "--replace-demo",
            action="store_true",
            help="Delete and recreate rows previously generated by this command.",
        )

    def handle(self, *args, **options):
        queryset = EstateProject.objects.filter(
            publication_status__in=["publish", "published"],
        ).order_by("id")

        if options["project_id"]:
            queryset = queryset.filter(pk=options["project_id"])

        if options["limit"]:
            queryset = queryset[: options["limit"]]

        created_totals = {
            "projects": 0,
            "sections": 0,
            "unit_types": 0,
            "prices": 0,
            "deposit_plans": 0,
            "installments": 0,
            "incentives": 0,
            "amenities": 0,
        }

        with transaction.atomic():
            for project in queryset:
                counts = self.seed_project(
                    project,
                    replace_demo=options["replace_demo"],
                )

                created_totals["projects"] += 1

                for key, value in counts.items():
                    created_totals[key] += value

                self.stdout.write(
                    self.style.SUCCESS(
                        f"{project.id}: {project.title} "
                        f"created={sum(counts.values())}"
                    )
                )

            if options["dry_run"]:
                transaction.set_rollback(True)
                self.stdout.write(
                    self.style.WARNING("DRY RUN — no changes committed.")
                )

        self.stdout.write("")
        self.stdout.write("Summary:")

        for key, value in created_totals.items():
            self.stdout.write(f"  {key}: {value}")

    def seed_project(
        self,
        project: EstateProject,
        *,
        replace_demo: bool,
    ) -> dict[str, int]:
        counts = {
            "sections": 0,
            "unit_types": 0,
            "prices": 0,
            "deposit_plans": 0,
            "installments": 0,
            "incentives": 0,
            "amenities": 0,
        }

        if replace_demo:
            self.delete_existing_demo_rows(project)

        location = project_location(project)
        developer = project.developer.strip() or "the developer"
        base_price = deterministic_base_price(project)

        if not project.sections.exists():
            EstateContentSection.objects.create(
                project=project,
                heading="Overview",
                html=(
                    f"<p><strong>{project.title}</strong> is a "
                    f"pre-construction community located in {location}.</p>"
                    f"<p>The development is presented by {developer} and "
                    "offers contemporary homes designed for families, "
                    "investors, and move-up buyers.</p>"
                    "<p>Residents will have convenient access to local "
                    "schools, shopping, parks, recreation, and major "
                    "transportation routes.</p>"
                ),
                display_order=0,
                source_key=f"{DEMO_PREFIX}overview",
                parser_owned=False,
            )
            counts["sections"] += 1

        unit_types = list(project.unit_types.order_by("display_order", "id"))

        if not unit_types:
            names = [
                "Townhomes",
                "Semi-detached homes",
                "Detached homes",
            ]

            for order, name in enumerate(names):
                unit_types.append(
                    EstateUnitType.objects.create(
                        project=project,
                        name=name,
                        description=(
                            "Contemporary layouts with modern finishes "
                            "and functional living spaces."
                        ),
                        display_order=order,
                        source_key=f"{DEMO_PREFIX}unit:{order}",
                        parser_owned=False,
                    )
                )
                counts["unit_types"] += 1

        if not project.prices.exists():
            price_steps = [
                Decimal("0"),
                Decimal("100000"),
                Decimal("250000"),
            ]

            for order, unit in enumerate(unit_types[:3]):
                amount = base_price + price_steps[order]

                EstatePrice.objects.create(
                    project=project,
                    unit_type=unit,
                    display_text=f"Starting from ${amount:,.0f}",
                    amount=amount,
                    currency="CAD",
                    display_order=order,
                    source_key=f"{DEMO_PREFIX}price:{order}",
                    parser_owned=False,
                )
                counts["prices"] += 1

        if not project.deposit_plans.exists():
            plan = EstateDepositPlan.objects.create(
                project=project,
                unit_type=unit_types[0] if unit_types else None,
                title="Standard deposit structure",
                display_order=0,
                source_key=f"{DEMO_PREFIX}deposit-plan:0",
                parser_owned=False,
            )
            counts["deposit_plans"] += 1

            installments = [
                ("On signing", "$10,000", "10000", None),
                ("Within 30 days", "$10,000", "10000", None),
                ("Within 60 days", "$10,000", "10000", None),
                ("Within 90 days", "$10,000", "10000", None),
                ("Within 150 days", "$20,000", "20000", None),
                ("Within 210 days", "Balance to 10%", None, "10"),
            ]

            for order, (
                milestone,
                amount_text,
                amount,
                percentage,
            ) in enumerate(installments):
                EstateDepositInstallment.objects.create(
                    plan=plan,
                    milestone=milestone,
                    amount_text=amount_text,
                    amount=Decimal(amount) if amount else None,
                    percentage=(
                        Decimal(percentage) if percentage else None
                    ),
                    display_order=order,
                    source_key=f"{DEMO_PREFIX}installment:0:{order}",
                    parser_owned=False,
                )
                counts["installments"] += 1

        if not project.incentives.exists():
            incentives = [
                "Décor centre credit",
                "Appliance package included",
                "Free assignment",
                "Capped development charges",
            ]

            for order, description in enumerate(incentives):
                EstateIncentive.objects.create(
                    project=project,
                    description=description,
                    display_order=order,
                    source_key=f"{DEMO_PREFIX}incentive:{order}",
                    parser_owned=False,
                )
                counts["incentives"] += 1

        if not project.amenities.exists():
            amenities = [
                f"Convenient location in {location}",
                "Nearby schools, parks, and recreation",
                "Access to shopping and everyday services",
                "Connections to major transportation routes",
            ]

            for order, description in enumerate(amenities):
                EstateAmenity.objects.create(
                    project=project,
                    description=description,
                    display_order=order,
                    source_key=f"{DEMO_PREFIX}amenity:{order}",
                    parser_owned=False,
                )
                counts["amenities"] += 1

        return counts

    def delete_existing_demo_rows(self, project: EstateProject) -> None:
        EstateDepositInstallment.objects.filter(
            plan__project=project,
            source_key__startswith=DEMO_PREFIX,
        ).delete()

        EstateDepositPlan.objects.filter(
            project=project,
            source_key__startswith=DEMO_PREFIX,
        ).delete()

        for model in [
            EstateContentSection,
            EstateUnitType,
            EstatePrice,
            EstateIncentive,
            EstateAmenity,
        ]:
            model.objects.filter(
                project=project,
                source_key__startswith=DEMO_PREFIX,
            ).delete()